name: Build and Release

on:
  push:
    branches:
      - main

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-20.04]
        arch: [amd64, arm64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up GCC
        run: sudo apt-get install gcc

      - name: Compile
        run: make

      - name: Upload server
        uses: actions/upload-artifact@v2
        with:
          name: libserver-${{ matrix.arch }}.so
          path: ./libserver.so

      - name: Upload client
        uses: actions/upload-artifact@v2
        with:
          name: libclient-${{ matrix.arch }}.so
          path: ./libclient.so

  release:
    runs-on: ubuntu-latest

    needs: [build]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Download libserver-amd64
        uses: actions/download-artifact@v2
        with:
          name: libserver-amd64.so
          path: ./libserver-amd64.so

      - name: Download libclient-amd64
        uses: actions/download-artifact@v2
        with:
          name: libclient-amd64.so
          path: ./libclient-amd64.so

      - name: Download libserver-arm64
        uses: actions/download-artifact@v2
        with:
          name: libserver-arm64.so
          path: ./libserver-arm64.so

      - name: Download libclient-arm64
        uses: actions/download-artifact@v2
        with:
          name: libclient-arm64.so
          path: ./libclient-arm64.so

      - name: Tag the repository
        id: tag
        run: |
          # See https://docs.github.com/en/get-started/using-git/dealing-with-special-characters-in-branch-and-tag-names
          TAG=v$(date -Iseconds | sed 's/[T:\+]/-/g')
          echo "$TAG"
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          git tag -a $TAG -m "Published version $TAG" ${GITHUB_SHA}
          git push origin $TAG

      - name: rename files
        run: |
          mv ./libserver-amd64.so/libserver.so ./libserver-amd64.so/libserver-amd64.so
          mv ./libclient-amd64.so/libclient.so ./libclient-amd64.so/libclient-amd64.so
          mv ./libserver-arm64.so/libserver.so ./libserver-arm64.so/libserver-arm64.so
          mv ./libclient-arm64.so/libclient.so ./libclient-arm64.so/libclient-arm64.so
          

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./libserver-amd64.so/libserver-amd64.so
            ./libclient-amd64.so/libclient-amd64.so
            ./libserver-arm64.so/libserver-arm64.so
            ./libclient-arm64.so/libclient-arm64.so
          tag_name: ${{ steps.tag.outputs.tag }}